baseURL = "https://dongocanh96.com"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
theme = "hermit-v2"

[languages]
  [languages.en]
    title = 'dongocanh96 - Portfolio'
    [languages.en.params]
      homeSubtitle = "⚔️ Peace was not an option! ⚔️"
    weight = 3

 
languageCode = "en-us"

pygmentsCodefences  = true
pygmentsUseClasses  = true

rssLimit = 10

copyright = "dongocanh96 16-08-2024"
enableEmoji = true

[frontmatter]
date = ["date", "publishDate", "lastmod"]
lastmod = ["lastmod", ":git", "date", "publishDate"]
publishDate = ["publishDate", "date"]
expiryDate = ["expiryDate"]


[params.author]
  name = "dongocanh96"
  about = "about-me"

[blackfriday]

[taxonomies]
  tag = "tags"

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]


[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  description = "A man of culture as well!"
  themeColor = "#494f5c"

  footerCopyright = "dongocanh96 16-08-2024"

  justifyContent = false

  relatedPosts = true
  code_copy_button = true

  homeSubtitlePrinter = true
  scrollToTop = true 
  global_mathjax = false
  readTime = true
  readTimeSeparator = "\u2026 \u23F2 Reading Time:"

  shareSocial = true

  pinned = "Pinned Posts"

  descriptionInPosts= true

  human = ["single","posts"]
  
  [[params.socialLinks]]
    name = "github"
    url = "https://github.com/dongocanh96"

  [[params.socialLinks]]
    name = "facebook"
    url = "https://www.facebook.com/dongocanh.tb"

  [[params.socialLinks]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/dongocanh96/"

[menu]

  [[menu.main]]
    name = "Posts"
    url = "posts/"
    weight = 10

  [[menu.main]]
    name = "About"
    url = "about-me/"
    weight = 20